### ISSUE TITLE
Trying to run a Qiime-produced seqs.fna file through Phylosift 

### ISSUE THREAD

**Issue by atremain** [gjospin/PhyloSift#412] opened 2013-05-23 17:31 UTC
Hi there,

I encounter this error when I attempt the './phylosift all' command on a seqs.fna file that was produced in Qiime: 

hmmalign(23223) malloc: **\* mmap(size=16777216) failed (error code=12)
**\* error: can't allocate region
**\* set a breakpoint in malloc_error_break to debug
Fatal exception (source file p7_trace.c, line 98):
malloc of size 1024 failed
hmmalign(23440) malloc: **\* mmap(size=16777216) failed (error code=12)
**\* error: can't allocate region
**\* set a breakpoint in malloc_error_break to debug
Fatal exception (source file esl_msa.c, line 565):
malloc of size 10387 failed

And here is another example using a different seqs.fna file:

hmmalign(22470) malloc: **\* mmap(size=16777216) failed (error code=12)
**\* error: can't allocate region
**\* set a breakpoint in malloc_error_break to debug
Fatal exception (source file p7_trace.c, line 97):
malloc of size 1024 failed
hmmalign(22813) malloc: **\* mmap(size=16777216) failed (error code=12)
**\* error: can't allocate region
**\* set a breakpoint in malloc_error_break to debug
Fatal exception (source file p7_trace.c, line 97):
malloc of size 1024 failed
Uncaught exception: Sys_error("/Users/atremain/share/phylosift/markers/V191.updated/CONTENTS.json: No such file or directory")
Fatal error: exception Sys_error("/Users/atremain/share/phylosift/markers/V191.updated/CONTENTS.json: No such file or directory")
hmmalign(23230) malloc: **\* mmap(size=16777216) failed (error code=12)
**\* error: can't allocate region
**\* set a breakpoint in malloc_error_break to debug
Fatal exception (source file p7_trace.c, line 100):
malloc of size 1024 failed

Both errors seems similar but I don't know what they mean or if they are avoidable. The two seqs.fna files that I was attempting to use were generated from the Qiime split_libraries.py command using mapping files that targeted individual samples.

Thanks!
Andrew

**Comment by gjospin** [comment] 2013-05-31 03:54
This looks like an hmmer problem. It could be that your OS does not like the version we packaged within PhyloSift.
What OS are you running? Can you post the full command you used to generate such output and maybe a sample (2 to 3 reads) of the sequences you are trying to run?

Thank you.
Sorry for the slow response time.

**Comment by atremain** [comment] 2013-06-03 17:28
No worries, thanks for the help. 

I'm running version 10.8.3. 

I lost track of the original commands I ran to get the above errors, but after running a very similar command - 

"MMIC-7571:phylosift_v1.0.0_01 atremain$ ./phylosift all ../Shared_Folder/Data_DogRhesus/slbruno/seqs.fna"
- I get a similar error as previously encountered: 

hmmalign(38080) malloc: **\* mmap(size=16777216) failed (error code=12)
**\* error: can't allocate region
**\* set a breakpoint in malloc_error_break to debug
Fatal exception (source file esl_msa.c, line 565):
malloc of size 10260 failed

And here's three reads from the input .fna file: 

> Bruno_0 HWI-M01533:30:000000000-A3LBP:1:1101:16655:1500 1:N:0: orig_bc=AACGCTAA new_bc=AACGCTAA bc_diffs=0
> TACGTAGGGTGCGAGCGTTGTCCGGAATTATTGGGCGTAAAGAGCTTGTAGGCGGTTTGTCGCGTCTGCTGTGAAAGACCGGGGCTTAACTCCGGTTCTGCAGTGGGTACGGGCAGACTAGAGTGTGGTAGGGGAGACTGGAATTCCTGGTGTAGCGGTGAAATGCGCAGATATCAGGAGGAACACCGATGGCGAAGGCAGGTCTCTGGGCCATTACTGACGCTGAGAAGCGAAAGCATGGGG
> Bruno_1 HWI-M01533:30:000000000-A3LBP:1:1101:16919:1500 1:N:0: orig_bc=AACGCTAA new_bc=AACGCTAA bc_diffs=0
> TACGATTAACCCAAACTAATAGGCCTACGGCGTAAAGCGTGTTCAAGATACTTTAACACTAAAGTTAAAACTTAACTAAGCCGTAAAAAGCTACAGTTATCATAAAATAAACCACGAAGGTGACTTTATAATAATCTGACTACACGATAGCTAAGACCCAAACTGGGATTAGAAACCCCGGTAGTCCGGCTGACTGACTACTTCAGTATC
> Bruno_2 HWI-M01533:30:000000000-A3LBP:1:1101:16419:1517 1:N:0: orig_bc=AACGCTAA new_bc=AACGCTAA bc_diffs=0
> TACGATTAACCCAAACTAATAGGCCTACGGCGTAAAGCGTGTTCAAGATACTTTAACACTAAAGTTAAAACTTAACTAAGCCGTAAAAAGCTACAGTTATCATAAAATAAACCACGAAGGTGACTTTATAATAATCTGACTACACGATAGCTAAGACCCAAACTGGGATTAGAAACCCCTGTAGTCCGGCTGACTGACTACTTCAGTATCTCGTATGCCGTCTTCTGCTTG

**Comment by gjospin** [comment] 2013-06-03 17:33
This doesn't seem to be in fasta format.
Read headers should start with >

**Comment by atremain** [comment] 2013-06-03 17:46
It's definitely in fasta format, it seems the > character was changed into a formatting command by the blog itself.

**Comment by koadman** [comment] 2013-06-03 21:57
agree, that doesn't look like any FastA I've seen before (unless the >
somehow got eaten by the email app).

On the other hand, phylosift could be more helpful with it's error
message. A sanity check on the input & error message like "Sorry your
data appears not to conform to FastA or FastQ formats, please check your
input file" would be an improvement.

**Comment by atremain** [comment] 2013-06-04 00:06
Didn't mean to close the issue... But the file is in fasta format, like I said before, the formatting on this site just changes a > to something else. For example, I'll make a mock fast below:

> title
> sequence

**Comment by koadman** [comment] 2013-07-19 04:21
I was not able to reproduce this issue on my laptop. Based on the hmmalign error message, it seems likely that hmmalign and other running programs exhausted all available RAM on @atremain 's computer. On my system with 8GB memory the analysis works using phylosift v1.0 beta on the sequences pasted in this thread. Closing, but please reopen if there's more to the issue than a simple out-of-memory condition.

**Closed as completed by koadman** 2013-07-19 04:21 UTC
