### ISSUE TITLE
UpdateDB.pm not creating submarkers.txt in devel

### ISSUE THREAD

**Issue by mayalowe** [gjospin/PhyloSift#160] opened 2012-04-25 20:24 UTC
When running the devel version of Phylosift on the GSL data, Phylosift looks for submarkers.txt in ~/share/phylosift/markers/ but it can't find it.  I do have a file named '.txt' in the markers directory, but it has a total size of a whopping 0 Kb.  UpdateDB.pm shows that it should be outputting a file named submarkers.txt, and the problem persists after indexing.  
I'm looking into it and am currently running the latest master build on the same data with no problems (yet).

**Comment by mayalowe** [comment] 2012-04-25 22:01
I should note that this is the case even when using --marker_url=http://edhar.genomecenter.ucdavis.edu/~koadman/phylosift_markers/devel/

STDERR:
ALIGNMENT FILE : /home/elowe/bin/phylosift_devel/PS_temp/north_arm_rozel.reads.fna/alignDir/concat.1.fasta
Running /home/elowe/bin/phylosift_devel/bin/pplacer  --verbosity 0 -j 1 -c /home/elowe/share/phylosift/markers/concat.updated "/home/elowe/bin/phylosift_devel/PS_temp/north_arm_rozel.reads.fna/alignDir/concat.1.fasta"
submarker read jplace
Unable to read from /home/elowe/share/phylosift/markers/submarkers.txt at /home/elowe/bin/phylosift_devel/bin/../lib/Phylosift/Utilities.pm line 92
    Phylosift::Utilities::ps_open('/home/elowe/share/phylosift/markers/submarkers.txt') called at /home/elowe/bin/phylosift_devel/bin/../lib/Phylosift/pplacer.pm line 114
    Phylosift::pplacer::load_submarkers() called at /home/elowe/bin/phylosift_devel/bin/../lib/Phylosift/pplacer.pm line 152
    Phylosift::pplacer::find_submarker_reads('place_file', '/home/elowe/bin/phylosift_devel/PS_temp/north_arm_rozel.reads...') called at /home/elowe/bin/phylosift_devel/bin/../lib/Phylosift/pplacer.pm line 235
    Phylosift::pplacer::make_submarker_placements('self', 'Phylosift::Phylosift=HASH(0x17a9d48)', 'marker', 'concat', 'chunk', 1, 'place_file', '/home/elowe/bin/phylosift_devel/PS_temp/north_arm_rozel.reads...') called at /home/elowe/bin/phylosift_devel/bin/../lib/Phylosift/pplacer.pm line 291
    Phylosift::pplacer::place_reads('self', 'Phylosift::Phylosift=HASH(0x17a9d48)', 'marker', 'concat', 'dna', 0, 'chunk', 1, 'reads', ...) called at /home/elowe/bin/phylosift_devel/bin/../lib/Phylosift/pplacer.pm line 65
    Phylosift::pplacer::pplacer('self', 'Phylosift::Phylosift=HASH(0x17a9d48)', 'marker_reference', 'ARRAY(0x299f760)', 'chunk', 1) called at /home/elowe/bin/phylosift_devel/bin/../lib/Phylosift/MarkerAlign.pm line 118
    Phylosift::MarkerAlign::MarkerAlign('self', 'Phylosift::Phylosift=HASH(0x17a9d48)', 'marker_reference', 'ARRAY(0x2fb6940)', 'chunk', 1) called at /home/elowe/bin/phylosift_devel/bin/../lib/Phylosift/FastSearch.pm line 100
    Phylosift::FastSearch::run_search('self', 'Phylosift::Phylosift=HASH(0x17a9d48)', 'marker_reference', 'ARRAY(0x2fb6940)') called at /home/elowe/bin/phylosift_devel/bin/../lib/Phylosift/Phylosift.pm line 457
    Phylosift::Phylosift::run_search('self', 'Phylosift::Phylosift=HASH(0x17a9d48)', 'cont', 0, 'marker', 'ARRAY(0x2fb6940)') called at /home/elowe/bin/phylosift_devel/bin/../lib/Phylosift/Phylosift.pm line 164
    Phylosift::Phylosift::run('Phylosift::Phylosift=HASH(0x17a9d48)', 'force', 1, 'custom', undef, 'cont', 0) called at bin/phylosift line 155

**Comment by gjospin** [comment] 2012-04-25 22:48
So I have narrowed it down a little bit. 
Pplacer.pm is trying to do the placement on submarkers. Which calls the load_submarkers function from that same module.

The problem is that submarkers.txt does not get created because the function in which it gets written (make_codon_submarkers from UpdateDB) never gets called.

**Comment by gjospin** [comment] 2012-04-25 22:51
Actually make_codon_submarker gets called in phylosift_dbupdate.pl

Maybe it needs to be restarted and repackaged.

**Comment by koadman** [comment] 2012-04-26 08:18
the submarkers.txt file gets created during the db update. 

This file does exist in the development markers, which are available here:
http://edhar.genomecenter.ucdavis.edu/~koadman/phylosift_markers/devel/markers.tgz

possibly something has prevented your phylosift from downloading and using the devel marker package. This raises a new issue which is that it's currently hard to tell what version of the markers you're using. One way the download could be getting blocked is if your local marker dir has a newer filesystem timestamp than the version on the server. Currently phylosift assumes your newer version is as new as or newer than what's on the server, and doesn't check if you've done something clever like switched to a different marker server URL!  You could move your current marker dir out of the way as a workaround.

**Comment by koadman** [comment] 2012-04-26 16:19
Closing because this isn't an issue, but created issue #165 to capture the problem with the client not downloading updates.

**Closed as completed by koadman** 2012-04-26 16:19 UTC
