### ISSUE TITLE
phylosift align error?

### ISSUE THREAD

**Issue by ewilbanks** [gjospin/PhyloSift#213] opened 2012-05-20 05:53 UTC
My phylosifting is breaking here at the align step.  Anyone know how I can specify the changes the error message suggests?

Thanks!

$ ./phylosift.pl align /home/ewilbanks/berry_project/PINK_BERRY_ASSEMBLE/assemblies/idba_ud/interleaved_illumina_w454/scaffold.fa
PhyloSift -- Phylogenetic analysis of genomes and metagenomes
(c) 2011, 2012 Aaron Darling and Guillaume Jospin

CITATION:
        PhyloSift. A. Darling, H. Bik, G. Jospin, J. A. Eisen. Manuscript in preparation

PhyloSift incorporates several other software packages, please consider also citing the following papers: [[...OMITTED]]

Error: requested HMM banded DP mx of 2253.93 Mb > 2048.00 Mb limit.

**Comment by koadman** [comment] 2012-05-20 11:42
This bug was fixed on devel a while ago, but the change has not been pushed to master branch yet. The issue is that cmalign needs more memory. You can either edit line 446 of your local copy of lib/Phylosift/MarkerAlign.pm to change:
`"$Phylosift::Utilities::cmalign -q --dna --tau 1e-6 "`
to:
`"$Phylosift::Utilities::cmalign -q --dna --tau 1e-6 --mxsize 2500 "`
or try the development branch of phylosift, packaged up here:
http://edhar.genomecenter.ucdavis.edu/~koadman/phylosift/devel/phylosift_latest.tar.bz2

**Closed as completed by koadman** 2012-05-20 11:42 UTC

**Comment by ewilbanks** [comment] 2012-05-20 22:56
thanks!

On Sun, May 20, 2012 at 4:42 AM, Aaron Darling <
reply@reply.github.com

> wrote:
> 
> This bug was fixed on devel a while ago, but the change has not been
> pushed to master branch yet. The issue is that cmalign needs more memory.
> You can either edit line 446 of your local copy of
> lib/Phylosift/MarkerAlign.pm to change:
> `"$Phylosift::Utilities::cmalign -q --dna --tau 1e-6 "`
> to:
> `"$Phylosift::Utilities::cmalign -q --dna --tau 1e-6 --mxsize 2500 "`
> or try the development branch of phylosift, packaged up here:
> 
> http://edhar.genomecenter.ucdavis.edu/~koadman/phylosift/devel/phylosift_latest.tar.bz2
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/gjospin/PhyloSift/issues/213#issuecomment-5808281

## 

"The obvious goal of any bacterium is to become bacteria."

Lizzy Wilbanks
Graduate Student, Eisen and Facciotti Labs
UC Davis, Microbiology Graduate Group
